apiVersion: v1
kind: Service
metadata:
    name: fileflow-front-svc
    namespace: file-flow
spec:
    type: ClusterIP
    selector:
        app: fileflow-front
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80