CREATE SEQUENCE IF NOT EXISTS groups_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE file_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    file_id    BIGINT,
    CONSTRAINT pk_file_comments PRIMARY KEY (id)
);

CREATE TABLE file_group_permissions
(
    permission VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    file_id    BIGINT       NOT NULL,
    group_id   BIGINT       NOT NULL,
    CONSTRAINT pk_file_group_permissions PRIMARY KEY (file_id, group_id)
);

CREATE TABLE file_user_permissions
(
    permission VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    file_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT pk_file_user_permissions PRIMARY KEY (file_id, user_id)
);

CREATE TABLE files
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_files PRIMARY KEY (id)
);

CREATE TABLE folders
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    folder_id BIGINT,
    name      VARCHAR(255),
    CONSTRAINT pk_folders PRIMARY KEY (id)
);

CREATE TABLE group_users
(
    joined_at TIMESTAMP WITHOUT TIME ZONE,
    group_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_group_users PRIMARY KEY (group_id, user_id)
);

CREATE TABLE groups
(
    id         BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    user_id    BIGINT       NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE file_comments
    ADD CONSTRAINT FK_FILE_COMMENTS_ON_FILE FOREIGN KEY (file_id) REFERENCES files (id);

ALTER TABLE file_comments
    ADD CONSTRAINT FK_FILE_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE file_group_permissions
    ADD CONSTRAINT FK_FILE_GROUP_PERMISSIONS_ON_FILE FOREIGN KEY (file_id) REFERENCES files (id);

ALTER TABLE file_group_permissions
    ADD CONSTRAINT FK_FILE_GROUP_PERMISSIONS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE file_user_permissions
    ADD CONSTRAINT FK_FILE_USER_PERMISSIONS_ON_FILE FOREIGN KEY (file_id) REFERENCES files (id);

ALTER TABLE file_user_permissions
    ADD CONSTRAINT FK_FILE_USER_PERMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE group_users
    ADD CONSTRAINT FK_GROUP_USERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_users
    ADD CONSTRAINT FK_GROUP_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);