apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-backend-config
  namespace: file-flow
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/app/*.log
      fields:
        component: java
        service: fileflow-backend
      fields_under_root: true
      multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
      multiline.negate: true
      multiline.match: after
      scan_frequency: 10s
      close_inactive: 5m

    output.logstash:
      hosts: ["server.file-flow.svc.cluster.local:5044"]

    processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_kubernetes_metadata:
        host: "${NODE_NAME}"
        matchers:
        - logs_path:
            logs_path: "/var/log/app/"

    logging.level: error
    logging.to_files: false 