apiVersion: v1
kind: Service
metadata:
    name: fileflow-svc
    namespace: file-flow
spec:
    type: ClusterIP
    selector:
        app: fileflow
    ports:
        -   protocol: TCP
            port: 8080
            targetPort: 8080