apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-backend-config
  namespace: file-flow
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      enabled: true
      paths:
        - /var/log/containers/fileflow-*.log
      fields:
        component: java
        service: fileflow-backend
      fields_under_root: true
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: log

    output.logstash:
      hosts: ["server.file-flow.svc.cluster.local:5044"]

    processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_kubernetes_metadata:
        host: "${NODE_NAME}"
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true

    logging.level: debug
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644 