apiVersion: apps/v1
kind: Deployment
metadata:
    name: fileflow-deployment
    namespace: file-flow
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fileflow
    template:
        metadata:
            labels:
                app: fileflow
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: fileflow
                    image: rafaelreis0/file_flow:latest
                    imagePullPolicy: Always
                    env:
                        -   name: APP_PROFILE
                            value: "k8s"
                        -   name: DB_HOST
                            value: "postgres-svc"
                        -   name: REDIS_HOST
                            value: "redis-svc"
                        -   name: SERVER_PORT
                            value: "8080"
                        # Configurações Graylog
                        -   name: GRAYLOG_HOST
                            value: "server.file-flow.svc.cluster.local"
                        -   name: GRAYLOG_PORT
                            value: "12201"
                        -   name: LOGGING_GELF_ENABLED
                            value: "true"
                        -   name: LOGGING_LEVEL_COM_YOURAPP
                            value: "INFO"
                    envFrom:
                        -   configMapRef:
                                name: postgres-config
                        -   configMapRef:
                                name: fileflow-config
                    ports:
                        -   containerPort: 8080
                            name: http
                # Sidecar Filebeat para coletar logs da aplicação
                -   name: filebeat
                    image: docker.elastic.co/beats/filebeat:8.11.0
                    args: [
                      "-c", "/etc/filebeat/filebeat.yml",
                      "-e",
                    ]
                    env:
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                    volumeMounts:
                    - name: filebeat-config
                      mountPath: /etc/filebeat
                    - name: varlogcontainers
                      mountPath: /var/log/containers
                      readOnly: true
                    - name: varlogpods
                      mountPath: /var/log/pods
                      readOnly: true
            volumes:
            - name: filebeat-config
              configMap:
                name: filebeat-backend-config
            - name: varlogcontainers
              hostPath:
                path: /var/log/containers
            - name: varlogpods
              hostPath:
                path: /var/log/pods
            restartPolicy: Always
