name: Testes do backend

on:
  push:
    branches:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Rodar testes
        run: docker-compose -f docker-compose.tests.yml up --build --force-recreate --abort-on-container-exit --exit-code-from app